// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvhBTtaO9G02-BWQxDa9SnbtT3yBirgaE',
    appId: '1:836869471377:web:113ab6341dda1d910fd330',
    messagingSenderId: '836869471377',
    projectId: 'ofa-compra',
    authDomain: 'ofa-compra.firebaseapp.com',
    storageBucket: 'ofa-compra.firebasestorage.app',
    measurementId: 'G-1FJ8Y6NMR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIRZQKX_XUuIVKVwm90JnCaSm4uvTjrxw',
    appId: '1:836869471377:android:34a4ea76da2e5e540fd330',
    messagingSenderId: '836869471377',
    projectId: 'ofa-compra',
    storageBucket: 'ofa-compra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcsXHuN_v1B7WCcAhNOjcUA9O32UaFCH4',
    appId: '1:836869471377:ios:68226a0a3f3548740fd330',
    messagingSenderId: '836869471377',
    projectId: 'ofa-compra',
    storageBucket: 'ofa-compra.firebasestorage.app',
    iosBundleId: 'com.delacruz.ofa.ofaShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcsXHuN_v1B7WCcAhNOjcUA9O32UaFCH4',
    appId: '1:836869471377:ios:68226a0a3f3548740fd330',
    messagingSenderId: '836869471377',
    projectId: 'ofa-compra',
    storageBucket: 'ofa-compra.firebasestorage.app',
    iosBundleId: 'com.delacruz.ofa.ofaShopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvhBTtaO9G02-BWQxDa9SnbtT3yBirgaE',
    appId: '1:836869471377:web:40ba9e6f810604170fd330',
    messagingSenderId: '836869471377',
    projectId: 'ofa-compra',
    authDomain: 'ofa-compra.firebaseapp.com',
    storageBucket: 'ofa-compra.firebasestorage.app',
    measurementId: 'G-FSFF2NRVC5',
  );

}